### ISSUE TITLE
Exception while trying do download data from InteractiveBrokers TWS

### ISSUE THREAD

**Issue by goldsam** [StockSharp/StockSharp#440]
When following the instructions in the [*Setup Hydra for work with TWS* YouTube video](https://www.youtube.com/watch?v=nXEvtiHQH5c), I get hundreds of instances of the following error:

```
Error	System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Ecng.Collections.SynchronizedDictionary`2.TryGetValue(TKey key, TValue& value)
   at Ecng.Collections.CollectionHelper.TryGetValue[TKey,TValue](IDictionary`2 dict, TKey key)
   at StockSharp.Server.Core.SubscriptionHolder`3.#[REDACTED](DataType [REDACTED], SecurityId #[REDACTED], Int64 #[REDACTED])
   at StockSharp.Server.Core.SubscriptionHolder`3.GetSubscriptions(Message message)
   at StockSharp.Server.Fix.FixServerChannel.#[REDACTED](Message #[REDACTED])
   at StockSharp.Messages.PassThroughMessageChannel.StockSharp.Messages.IMessageChannel.SendInMessage(Message message)
   at StockSharp.Hydra.Core.Server.HydraServer.TrySendByFixImpl(Message message)
```

Somehow, a `null` values is being used as a key in a Dictionary lookup.

My goal is to download candle for NVDA
![image](https://github.com/user-attachments/assets/67802238-fb9e-4a1c-8451-dc0d177b46ed)

**Comment by mikasoukhov** [comment]
Thank you for the feedback regarding the issue with downloading data through InteractiveBrokers TWS. Could you please specify at which point the error occurs? Is it when trying to download data using Hydra itself, or does it happen when attempting to download data from Hydra using another program?

**Comment by goldsam** [comment]
When using Hydra itself

**Comment by goldsam** [comment]
Have you been able to reproduce the issue? Let me know if there's anything I can do to help.

**Comment by dadocsis** [comment]
I recently went through a rough process of getting Hyrda to download data from TWS. Some things I would try... Shorten the timeframe (just to test), Uncheck the "Off" box..

**Comment by goldsam** [comment]
![image](https://github.com/user-attachments/assets/9b27078a-fec3-4b92-9e8d-69dafadfd226)

**Comment by goldsam** [comment]
@dadocsis The shortest timeframe you can configure is 1 day. Enabling/disabling makes no difference. Configuring so only one data set is listed also makes no difference. Just hundreds and and hundreds of the same exception above.

**Comment by mikasoukhov** [comment]
Hello,

We will release a fix in the upcoming release. In the meantime, please disable the server mode when downloading (you can enable it again after the download is complete). The issue lies specifically with the server mode. You can simply toggle it off as described in our [documentation](https://doc.stocksharp.com/topics/hydra/server_mode/settings.html).

Also, please note that our primary communication channels are email or our Telegram chat. GitHub is used for only a small part of our projects, and not many of our team members are active here.

Best regards,

**Comment by goldsam** [comment]
Sounds good. Thank you.
